apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phonecall
commonLabels:
  app: phone-to-sms
  app.kubernetes.io/name: phone-to-sms
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
