apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-to-sms
spec:
  template:
    spec:
      containers:
      - name: phone-to-sms
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
